// generated by unplugin-vue-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ICarbonMoon: typeof import('~icons/carbon/moon')['default']
    ICarbonSun: typeof import('~icons/carbon/sun')['default']
    'IMdi:close': typeof import('~icons/mdi/close')['default']
    'IMdi:windowMaximize': typeof import('~icons/mdi/window-maximize')['default']
    'IMdi:windowMinimize': typeof import('~icons/mdi/window-minimize')['default']
  }
}

export { }
